---
- name: Initizaling kubeadm
  command: kubeadm init --apiserver-advertise-address=192.168.88.10 --apiserver-cert-extra-sans=192.168.88.10 --pod-network-cidr=192.168.88.0/24
  become: true

- name: Configure kubectl
  shell: mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config
  become: true

- name: Download Weave Scope
  command: curl -L https://cloud.weave.works/launch/k8s/weavescope.yaml
  become: true

- name: Create weave
  command: kubectl create -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml'

- name: Create key to enter on Cluster
  command: kubeadm token create --print-join-command
  register: kubeadm_join
  become: true

- name: "Save kubeadm_join log"
  local_action: copy content="{{ kubeadm_join.stdout_lines[0] }}" dest="roles/k8s-node/files/kubeadm_join"
  become_method: sudo
  become: true
