---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
  become: true

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: true

- name: Configure daemon docker | SystemD
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - Reload daemon
    - Restar docker service
  become: true

- name: Installing depends
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python"
    - "vim"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg-agent"
    - "software-properties-common"
  become: true

- name: Add an Apt signing key Docker.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Add Fingerprint repo Docker.
  command: apt-key fingerprint 0EBFCD88

- name: Add repository Docker.
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Update repos
  command: apt-get update
  become: true

- name: install Docker
  command: apt-get install docker-ce docker-ce-cli containerd.io -y
  become: true
