---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
  become: true

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: true

- name: Installing depends
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "python"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg-agent"
    - "software-properties-common"
  become: true

- name: Add an Apt signing key Docker.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_os_family == 'Debian'
  become: true

- name: Add Fingerprint repo Docker.
  command: apt-key fingerprint 0EBFCD88

- name: Add repository Docker.
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  when: ansible_os_family == 'Debian'
  become: true

- name: Add an Apt signing key K8S.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  when: ansible_os_family == 'Debian'
  become: true

- name: Add repository K8S.
  apt_repository:
    filename: kubernetes
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
  when: ansible_os_family == 'Debian'
  become: true

- name: Update repos
  apt:
    update_cache: yes
  become: true

- name: install Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
  become: true



- name: Create docker folder
  file:
    path: /etc/docker
    state: directory
  become: true

- name: Configure daemon docker | SystemD
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - Reload daemon
    - Restar docker service
  become: true

- name: Install packages K8S.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "kubeadm"
    - "kubectl"
    - "kubelet"
  become: true

